services:
  - type: web
    name: vehicle-detection
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python download_model.py
    startCommand: streamlit run traffic22.py
    envVars:
      - key: PORT
        value: 8501
      - key: PYTHONUNBUFFERED
        value: true
      - key: YOLO_MODEL_URL
        sync: false 